version: 0.2
phases:
  install:
    commands:
      - make install

  build:
    commands:
      - make test
      - make lint
      - make format
      - make all
artifacts:
  files:
    - '**/*'
  name: Artifact
  discard-paths: no
